title: "Matt Akbarian"
baseurl: ""

first-name: 'Mehdi'
last-name: 'Akbarian Rastaghi'
job-title: 'Software Developer at Aimsio and Founder of <a href="https://sakkku.cloud/En">SAKKU Cloud Platform</a>'
profpic: '/resources/img/profilepic.jpg'
profpic-retina: '/resources/img/profilepic@2x.jpg'
twitter: mehdiakbn
email: 'mehdi74akbarian@gmail.com'
github: 'makbn'
location: 'Calgary, AB, Canada'
location-url: "https://goo.gl/maps/tTXYvHFQ9rj6GyiLA"

# For syntax highlighting, the primary programming langauge you intend to use in
# blog articles. By default, Google's prettify will be used for this programming
# language, as per the instructions here: https://github.com/google/code-prettify
# For example, if I indicate `scala`, all pre/code blocks will have the `lang-scala`
# class added to the markup, triggering prettify to highlight the syntax as Scala.
primarylanguage: java
# To sidestep the default language for syntax highlighting set here, you can be
# explicit in your blog articles with the langauge you'd prefer to use. E.g.,
# <pre>
#   <code class="prettyprint lang-ruby">
#    ..ruby code here...
#   </code>
# </pre>

# categories:
#   blog:
#     permalink: /blog/:title.html

# Settings for blog RSS feed
name: "Matt Akbarian"
description: "Hello! I am Matt (Mehdi), a proud alumnus of the University of Alberta and a software developer at Aimsio. I am passionate about technology and dedicated to delivering excellence in software development. I aim to make a positive impact in the tech industry, and I am excited to continue growing and learning alongside my talented colleagues at Aimsio."
url: "https://makbn.giithub.io"
tagline: "Matt Akbarian Rastaghi Page, Software Engineer, Data Engineer"

permalink: /:categories/:title.html
# markdown: redcarpet
highlighter: null

sass:
  style: compressed

livereload: true

plugins:
  - jekyll-seo-tag


social:
  name: Mehdi Akbarian Rastaghi
  links:
    - https://www.linkedin.com/in/mehdiakbarian/
    - https://github.com/makbn
    - https://apps.ualberta.ca/directory/person/makbaria
    - https://www.facebook.com/makbn
    - https://scholar.google.com/citations?user=tXqn5GEAAAAJ&hl=en
    - https://stackoverflow.com/users/4708874/mehdi-akbarian-rastaghi
